language: c

env:
  matrix:
    - NGINX_VERSION=1.13.7

sudo: true    

install:
  - sudo apt-get install libpcre3 libpcre3-dev zlib1g-dev libssl-dev
  - cd && wget https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz && tar -xzf nginx-$NGINX_VERSION.tar.gz
  - cd $TRAVIS_BUILD_DIR && NGINX_SRC_DIR=$HOME/nginx-$NGINX_VERSION NGINX_DEBUG=no DYNAMIC_MODULE=yes ./configure --with-http_ssl_module

script:
  - make
